### ISSUE TITLE
Reporting wrong node?

### ISSUE THREAD

**Issue by jkulwicki** [WinserverSupport/wcSDK#5]
Hector, 

Thank you for removing the wcbasic-cmdline.cs file. The project now compiles great. 

   However I just noticed that when wcDoor32-example1 runs, it is reporting node #3 as well as Door node #3, but I am logged on my BBS on node #2. Is this expected behavior?

Thanks!

**Comment by WinserverSupport** [comment]
Yes,  when a door starts, it is a CLONE of user's session, but it gets a specific node number.   If the door writes an activity, check out wcNode or Who's Online to see the two different activities.

**Comment by WinserverSupport** [comment]
Take the look at the C++ simple examples in cpp/examples/door32, like dortst32.cpp or wcDoor32-example.cpp.  All Wildcat! door apps call DoorInitialize() to do the cloning.    Then just call WildcatLoggedIn() to see who you are.  That is what the C# classes do.   At that point, the door is responsible to doing the keyboard input handling.

**Comment by jkulwicki** [comment]
Hector,

Thanks for the explanation. I was under the assumption it would display the
actual user's BBS node. Not be assigned its own. That's all.

I appreciate the reply! Thanks for fixing the example file.

-Jim

**Comment by WinserverSupport** [comment]
The top level reason:   For the Clone session, it has to be a new node because its not the same process (EXE).   When you are spawn a different APP within the same main thread, like a WCX running another WCX , then its the same number, but when 2nd EXE is started (WCX starting an EXE), a new thread context and node is required.
